# Generated by Django 6.0.4 on 2026-04-15 09:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_time', models.DateTimeField()),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('work_duration', models.PositiveIntegerField(blank=True, help_text='Durée de travail en minutes (calculée automatiquement)', null=True)),
                ('late_minutes', models.PositiveIntegerField(default=0, help_text='Minutes de retard (calculées automatiquement)')),
                ('date', models.DateField(help_text='Date dérivée automatiquement du check_in_time')),
                ('status', models.CharField(choices=[('active', 'En cours'), ('completed', 'Terminé')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Présence',
                'verbose_name_plural': 'Présences',
                'db_table': 'attendances',
                'ordering': ['-date', '-check_in_time'],
            },
        ),
        migrations.CreateModel(
            name='QRCodeSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(editable=False, max_length=64, unique=True)),
                ('type', models.CharField(choices=[('CHECK_IN', 'Entrée'), ('CHECK_OUT', 'Sortie')], max_length=10)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Session QR Code',
                'verbose_name_plural': 'Sessions QR Code',
                'db_table': 'qr_code_sessions',
                'ordering': ['-created_at'],
            },
        ),
    ]
