# Generated by Django 6.0.4 on 2026-04-15 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrcodesession',
            name='is_used',
        ),
        migrations.RemoveField(
            model_name='qrcodesession',
            name='used_at',
        ),
        migrations.RemoveField(
            model_name='qrcodesession',
            name='used_by',
        ),
    ]
